NA = "N/A"


field_names = {
    "data_realizzazione_cedola": "cod_data_realizzazione",
    "coupon_valuation_date": "cod_data_osservazione",
    "coupon_payment_date": "cod_coupon_payment_date",
    "importo_cedola": "cod_importo_cedola",
    "callable_valuation_date": "cod_callable_valuation_date",
    "underlying_description": "cod_underlying_description",
    "underlying_type": "cod_underlying_type",
    "underlying_stockexchange": "cod_underlying_stockexchange",
    "underlying_bloombergcode": "cod_underlying_bloombergcode",
    "isin": "cod_isin",
    "fixing_eur": "cod_fixing_eur",
    "barriera_eur": "cod_barriera_eur",
    "coupon_eur": "cod_coupon_eur",
    "barrier": "cod_barrier",
    "liv_att_cedola_perc": "cod_liv_att_cedola_perc",
    "liv_fixing_iniziale": "cod_liv_fixing_iniziale",
    "livello_cap": "cod_livello_cap",
    "nominal": "cod_nominal",
    "liv_fix_fin": "cod_liv_fix_fin",
    "issuer_desc": "cod_issuer_desc",
    "issue_date": "cod_issue_date",
    "market": "cod_market",
    "perf_peg": "cod_perf_peg",
    "inv_min": "cod_inv_min",
    "unconditional_protection": "cod_unconditional_protection",
    "currency": "cod_currency",
    "description": "cod_description",
    "strike_date": "cod_strike_date",
    "data_negoziazione": "cod_data_negoziazione",
    "final_valuation_date": "cod_final_valuation_date",
    "liv_fix_ini": "cod_liv_fix_ini",
    "mod_pagamento": "cod_mod_pagamento",
    "tasso_cedola_cond": "cod_tasso_cedola_cond",
    "unconditional_coupon": "cod_unconditional_coupon",
    "rischio_cambio": "cod_rischio_cambio",
    "importo_rimborso": "cod_importo_rimborso",
    "importo_protezione_capitale": "cod_importo_protezione_capitale",
    "leva_cedolare": "cod_leva_cedolare",
    "callable": "cod_callable",
    "underlying_isin": "cod_underlying_isin",
    "putable": "cod_putable",
    "expiry_day": "cod_expiry_day",
    "periodo": "cod_periodo",
    "autocall": "cod_autocall",
    "callable": "cod_callable",
    "memory": "cod_memory",
    "underlying_strike_level": "cod_underlying_strike_level",
    "autocall_valuation_date": "cod_autocall_valuation_date",
    "autocall_payment_date": "cod_autocall_payment_date",
    "liv_attiv_cedola": "cod_liv_attiv_cedola",
    "barrier_autocall": "cod_barrier_autocall",
***REMOVED***

renaming = {
    "data_realizzazione_cedola": "Data di Realizzazione della Cedola",
    "coupon_valuation_date": "Data di Osservazione della Cedola",
    "coupon_payment_date": "Data di Pagamento della Cedola Condizionale",
    "importo_cedola": "Importo della Cedola Condizionale",
    "callable_valuation_date": "Giorno di Monitoraggio del Rimborso",
    "underlying_description": "underlying_description",
    "underlying_type": "underlying_type",
    "underlying_stockexchange": "Borsa",
    "underlying_bloombergcode": "Bloomberg Ticker",
    "isin": "ISIN",
    "fixing_eur": "Fixing in EUR",
    "barriera_eur": "Barriera in EUR",
    "coupon_eur": "Coupon in EUR",
    "barrier": "Livello Barriera %",
    "liv_att_cedola_perc": "Livello Attivazione Cedola %",
    "liv_fixing_iniziale": "Livello Fixing Iniziale %",
    "livello_cap": "Livello Cap %",
    "nominal": "Prezzo",
    "liv_fix_fin": "Livello Fixing Finale",
    "issuer_desc": "issuer_desc",
    "issue_date": "Data Emissione",
    "market": "Quotazione",
    "underlying_isin": "ISIN Sottostante",
    "perf_peg": "Performance Peggiore",
    "inv_min": "Investimento Minimo",
    "unconditional_protection": "Garanzia Minima %",
    "currency": "Valuta del Prodotto",
    "description": "Descrizione",
    "strike_date": "Data Fixing Iniziale",
    "data_negoziazione": "Data Emissione",
    "final_valuation_date": "Data Fixing Finale",
    "liv_fix_ini": "Livello Fixing Iniziale",
    "mod_pagamento": "Modalità Pagamento",
    "tasso_cedola_cond": "Tasso Cedola Condizionato",
    "unconditional_coupon": "Cedola Garantita %",
    "rischio_cambio": "Rischio Cambio",
    "importo_rimborso": "Importo di Rimborso Massimo",
    "importo_protezione_capitale": "Importo di Protezione del Capitale",
    "leva_cedolare": "leva_cedolare",
    "callable": "Callable",
    "putable": "Putable",
    "expiry_day": "Data di Rimborso",
    "periodo": "Periodo",
    "autocall": "Autocallable",
    "callable": "callable",
    "memory": "Effetto Memoria",
    "underlying_strike_level": "Strike Level %",
    "autocall_valuation_date": "Data di Osservazione Autocall",
    "autocall_payment_date": "Data di Pagamento Autocall",
    "liv_attiv_cedola": "Livello di Attivazione Cedola",
    "barrier_autocall": "Livello di Attivazione Autocall",
***REMOVED***


sections = """
        {
    "section0": {
      "name": "Informazioni di base",
      "list": [
        "currency",
        "issue_date",
        "periodo",
        "expiry_day",
        "nominal",
        "market",
        "inv_min",
        "strike_date",
        "data_negoziazione",
        "mod_pagamento",
        "description",
        "issuer_desc"
      ]
    ***REMOVED***,
    "section1": {
      "name": "Cedole e Autocall",
      "list": [
        "coupon_valuation_date",
        "liv_attiv_cedola",
        "coupon_payment_date",
        "importo_cedola",
        "autocall_valuation_date",
        "barrier_autocall",
        "autocall_payment_date"
      ]
    ***REMOVED***,
    "section2": {
      "name": "Sottostanti e Parametri di Mercato",
      "list": [
        "underlying_description",
        "underlying_type",
        "underlying_stockexchange",
        "underlying_bloombergcode",
        "underlying_isin",
        "fixing_eur",
        "barriera_eur",
        "coupon_eur",
        "underlying_strike_level",
        "liv_fixing_iniziale",
        "liv_att_cedola_perc",
        "barrier",
        "livello_cap"
      ]
    ***REMOVED***,
    "section3": {
      "name": "Dati Finanziari",
      "list": [
        "liv_fix_fin",
        "perf_peg",
        "unconditional_protection",
        "final_valuation_date",
        "liv_fix_ini",
        "tasso_cedola_cond",
        "unconditional_coupon",
        "rischio_cambio",
        "importo_rimborso",
        "importo_protezione_capitale",
        "leva_cedolare"
      ]
    ***REMOVED***
***REMOVED***
        """

data_array = [
    "data_realizzazione_cedola",
    "coupon_valuation_date",
    "coupon_payment_date",
    "importo_cedola",
    "callable_valuation_date",
    "underlying_description",
    "underlying_type",
    "underlying_stockexchange",
    "underlying_bloombergcode",
    "isin",
    "underlying_isin",
    "fixing_eur",
    "barriera_eur",
    "coupon_eur",
    "barrier",
    "liv_att_cedola_perc",
    "liv_fixing_iniziale",
    "livello_cap",
    "nominal",
    "liv_fix_fin",
    "issuer_desc",
    "issue_date",
    "market",
    "perf_peg",
    "inv_min",
    "unconditional_protection",
    "currency",
    "description",
    "strike_date",
    "data_negoziazione",
    "final_valuation_date",
    "liv_fix_ini",
    "mod_pagamento",
    "tasso_cedola_cond",
    "unconditional_coupon",
    "rischio_cambio",
    "importo_rimborso",
    "importo_protezione_capitale",
    "leva_cedolare",
    "callable",
    "putable",
    "expiry_day",
    "periodo",
    "autocall",
    "callable",
    "memory",
    "underlying_strike_level",
    "autocall_valuation_date",
    "autocall_payment_date",
    "liv_attiv_cedola",
    "barrier_autocall",
]

TRUE = "true"
FALSE = "false"

allow_null = {
    "data_realizzazione_cedola": FALSE,
    "coupon_valuation_date": TRUE,
    "coupon_payment_date": FALSE,
    "importo_cedola": FALSE,
    "callable_valuation_date": FALSE,
    "underlying_description": FALSE,
    "underlying_type": FALSE,
    "underlying_stockexchange": FALSE,
    "underlying_bloombergcode": FALSE,
    "isin": FALSE,
    "fixing_eur": FALSE,
    "barriera_eur": TRUE,
    "coupon_eur": TRUE,
    "barrier": TRUE,
    "liv_att_cedola_perc": TRUE,
    "liv_fixing_iniziale": TRUE,
    "livello_cap": TRUE,
    "nominal": FALSE,
    "liv_fix_fin": TRUE,
    "issuer_desc": FALSE,
    "underlying_isin": FALSE,
    "issue_date": FALSE,
    "market": FALSE,
    "perf_peg": TRUE,
    "inv_min": FALSE,
    "unconditional_protection": TRUE,
    "currency": FALSE,
    "description": FALSE,
    "strike_date": FALSE,
    "data_negoziazione": FALSE,
    "final_valuation_date": TRUE,
    "liv_fix_ini": TRUE,
    "mod_pagamento": FALSE,
    "tasso_cedola_cond": TRUE,
    "unconditional_coupon": TRUE,
    "rischio_cambio": TRUE,
    "importo_rimborso": TRUE,
    "importo_protezione_capitale": TRUE,
    "leva_cedolare": TRUE,
    "callable": FALSE,
    "putable": FALSE,
    "expiry_day": FALSE,
    "periodo": FALSE,
    "autocall": FALSE,
    "callable": FALSE,
    "memory": FALSE,
    "underlying_strike_level": TRUE,
    "autocall_valuation_date": FALSE,
    "autocall_payment_date": FALSE,
    "liv_attiv_cedola": TRUE,
    "barrier_autocall": FALSE,
***REMOVED***

# extra info for json
INT = "Integer"
FLOAT = "Float"
STRING = "String"
DATE = "Date"
BOOL = "Boolean"
LIST_STRING = "List of String"
LIST_DATE = "List of Date"
LIST_FLOAT = "List of Float"

type_of = {
    "data_realizzazione_cedola": DATE,
    "coupon_valuation_date": DATE,
    "coupon_payment_date": DATE,
    "importo_cedola": FLOAT,
    "callable_valuation_date": DATE,
    "underlying_description": STRING,
    "underlying_type": STRING,
    "underlying_stockexchange": STRING,
    "underlying_bloombergcode": STRING,
    "isin": STRING,
    "fixing_eur": FLOAT,
    "barriera_eur": FLOAT,
    "coupon_eur": FLOAT,
    "barrier": FLOAT,
    "liv_att_cedola_perc": FLOAT,
    "liv_fixing_iniziale": FLOAT,
    "livello_cap": FLOAT,
    "nominal": FLOAT,
    "liv_fix_fin": FLOAT,
    "issuer_desc": STRING,
    "issue_date": DATE,
    "market": FLOAT,
    "underlying_isin": STRING,
    "perf_peg": FLOAT,
    "inv_min": FLOAT,
    "unconditional_protection": FLOAT,
    "currency": STRING,
    "description": STRING,
    "strike_date": DATE,
    "data_negoziazione": DATE,
    "final_valuation_date": DATE,
    "liv_fix_ini": FLOAT,
    "mod_pagamento": STRING,
    "tasso_cedola_cond": FLOAT,
    "unconditional_coupon": FLOAT,
    "rischio_cambio": STRING,  # Assuming it's a description or currency code
    "importo_rimborso": FLOAT,
    "importo_protezione_capitale": FLOAT,
    "leva_cedolare": FLOAT,
    "callable": STRING,  # Assuming it's a feature description, could be BOOLEAN if true/false
    "putable": STRING,  # Same as callable
    "expiry_day": DATE,
    "periodo": INT,  # Assuming it refers to a time period in days/months/years
    "autocall": STRING,  # Assuming it's a feature description, could be BOOLEAN if true/false
    "callable": STRING,  # Same as autocall
    "memory": STRING,  # Assuming it's a description, could be BOOLEAN if true/false
    "underlying_strike_level": FLOAT,
    "autocall_valuation_date": DATE,
    "autocall_payment_date": DATE,
    "liv_attiv_cedola": FLOAT,
    "barrier_autocall": FLOAT,
***REMOVED***


PERCENT = "%"
EURO = "€"
YEARS = "anni"
CAPS = "CAPS"
model_of = {
    "data_realizzazione_cedola": NA,
    "coupon_valuation_date": NA,
    "coupon_payment_date": NA,
    "importo_cedola": EURO,
    "callable_valuation_date": NA,
    "underlying_description": NA,
    "underlying_type": NA,
    "underlying_stockexchange": CAPS,
    "underlying_bloombergcode": CAPS,
    "isin": CAPS,
    "fixing_eur": EURO,
    "barriera_eur": EURO,
    "coupon_eur": EURO,
    "barrier": PERCENT,
    "liv_att_cedola_perc": PERCENT,
    "liv_fixing_iniziale": PERCENT,
    "livello_cap": PERCENT,
    "nominal": EURO,
    "liv_fix_fin": PERCENT,
    "issuer_desc": CAPS,
    "issue_date": NA,
    "market": EURO,
    "underlying_isin": CAPS,
    "perf_peg": PERCENT,
    "inv_min": EURO,
    "unconditional_protection": PERCENT,
    "currency": NA,
    "description": NA,
    "strike_date": NA,
    "data_negoziazione": NA,
    "final_valuation_date": NA,
    "liv_fix_ini": PERCENT,
    "mod_pagamento": NA,
    "tasso_cedola_cond": PERCENT,
    "unconditional_coupon": PERCENT,
    "rischio_cambio": NA,
    "importo_rimborso": EURO,
    "importo_protezione_capitale": EURO,
    "leva_cedolare": PERCENT,
    "callable": NA,
    "putable": NA,
    "expiry_day": NA,
    "periodo": YEARS,
    "autocall": NA,
    "callable": NA,
    "memory": NA,
    "underlying_strike_level": PERCENT,
    "autocall_valuation_date": NA,
    "autocall_payment_date": NA,
    "liv_attiv_cedola": PERCENT,
    "barrier_autocall": PERCENT,
***REMOVED***


decimals_of = {
    "data_realizzazione_cedola": NA,
    "coupon_valuation_date": NA,
    "coupon_payment_date": NA,
    "importo_cedola": 2,
    "callable_valuation_date": NA,
    "underlying_description": NA,
    "underlying_type": NA,
    "underlying_stockexchange": NA,
    "underlying_bloombergcode": NA,
    "isin": NA,
    "fixing_eur": 2,
    "barriera_eur": 2,
    "coupon_eur": 2,
    "underlying_isin": NA,
    "barrier": 2,
    "liv_att_cedola_perc": 2,
    "liv_fixing_iniziale": 2,
    "livello_cap": 2,
    "nominal": 2,
    "liv_fix_fin": 2,
    "issuer_desc": NA,
    "issue_date": NA,
    "market": 2,
    "perf_peg": 2,
    "inv_min": 2,  # Assuming this refers to an amount, hence 2 decimals.
    "unconditional_protection": 2,
    "currency": NA,
    "description": NA,
    "strike_date": NA,
    "data_negoziazione": NA,
    "final_valuation_date": NA,
    "liv_fix_ini": 2,
    "mod_pagamento": NA,
    "tasso_cedola_cond": 2,
    "unconditional_coupon": 2,
    "rischio_cambio": NA,
    "importo_rimborso": 2,
    "importo_protezione_capitale": 2,
    "leva_cedolare": 2,
    "callable": NA,
    "putable": NA,
    "expiry_day": NA,
    "periodo": NA,
    "autocall": NA,
    "callable": NA,
    "memory": NA,
    "underlying_strike_level": 2,
    "autocall_valuation_date": NA,
    "autocall_payment_date": NA,
    "liv_attiv_cedola": 2,
    "barrier_autocall": 2,
***REMOVED***


PERCENT_RANGE = []
ISIN_RANGE = []
DATE_RANGE = []

SRI_RANGE = []
NO_RANGE = []

range_of = {
    "data_realizzazione_cedola": DATE_RANGE,
    "coupon_valuation_date": DATE_RANGE,
    "coupon_payment_date": DATE_RANGE,
    "importo_cedola": NO_RANGE,  # Could have a minimum value but not a fixed range
    "callable_valuation_date": DATE_RANGE,
    "underlying_description": NO_RANGE,
    "underlying_type": NO_RANGE,
    "underlying_stockexchange": NO_RANGE,
    "underlying_bloombergcode": NO_RANGE,
    "isin": ISIN_RANGE,
    "fixing_eur": NO_RANGE,
    "barriera_eur": NO_RANGE,
    "coupon_eur": NO_RANGE,
    "barrier": PERCENT_RANGE,
    "liv_att_cedola_perc": PERCENT_RANGE,
    "liv_fixing_iniziale": PERCENT_RANGE,
    "livello_cap": PERCENT_RANGE,
    "nominal": NO_RANGE,
    "liv_fix_fin": PERCENT_RANGE,
    "issuer_desc": NO_RANGE,
    "issue_date": DATE_RANGE,
    "market": NO_RANGE,
    "underlying_isin": ISIN_RANGE,
    "perf_peg": NO_RANGE,  # Assuming it's a performance measure, could be PERCENT_RANGE if it's a percentage
    "inv_min": NO_RANGE,  # Minimum investment might have a lower limit but not a fixed range
    "unconditional_protection": PERCENT_RANGE,
    "currency": NO_RANGE,
    "description": NO_RANGE,
    "strike_date": DATE_RANGE,
    "data_negoziazione": DATE_RANGE,
    "final_valuation_date": DATE_RANGE,
    "liv_fix_ini": PERCENT_RANGE,
    "mod_pagamento": NO_RANGE,
    "tasso_cedola_cond": PERCENT_RANGE,
    "unconditional_coupon": PERCENT_RANGE,
    "rischio_cambio": NO_RANGE,  # Assuming this is a feature or description
    "importo_rimborso": NO_RANGE,
    "importo_protezione_capitale": NO_RANGE,
    "leva_cedolare": PERCENT_RANGE,
    "callable": NO_RANGE,
    "putable": NO_RANGE,
    "expiry_day": DATE_RANGE,
    "periodo": NO_RANGE,  # Assuming it's a duration, might have a minimum but not a fixed range
    "autocall": NO_RANGE,
    "callable": NO_RANGE,
    "memory": NO_RANGE,
    "underlying_strike_level": PERCENT_RANGE,
    "autocall_valuation_date": DATE_RANGE,
    "autocall_payment_date": DATE_RANGE,
    "liv_attiv_cedola": PERCENT_RANGE,
    "barrier_autocall": PERCENT_RANGE,
***REMOVED***
